version: "3.9"
services:
  graphql:
    ports:
      - 3002:3002
    networks:
      - rabbitmq_network
    working_dir: /app
    tty: true
    stdin_open: true
    build:
      context: .
    entrypoint: "sh docker-entrypoint.sh"
    command: bin/rails s -b 0.0.0.0 -p 3002
    volumes:
      - .:/app
networks:
  rabbitmq_network:
    name: rabbitmq_network
    external: true